// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4mqFJekvji451KgKbegxWF
// Component: t9-VfU8p_8
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_untitled_project.module.css"; // plasmic-import: 4mqFJekvji451KgKbegxWF/projectcss
import * as sty from "./PlasmicCc.module.css"; // plasmic-import: t9-VfU8p_8/css

export const PlasmicCc__VariantProps = new Array();

export const PlasmicCc__ArgProps = new Array();

function PlasmicCc__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCc__ArgProps,
      internalVariantPropNames: PlasmicCc__VariantProps
    });

    return PlasmicCc__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCc";
  } else {
    func.displayName = `PlasmicCc.${nodeName}`;
  }
  return func;
}

export const PlasmicCc = Object.assign(
  // Top-level PlasmicCc renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCc
    internalVariantProps: PlasmicCc__VariantProps,
    internalArgProps: PlasmicCc__ArgProps
  }
);

export default PlasmicCc;
/* prettier-ignore-end */
